version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=dynamicsmind
    - POSTGRES_PASSWORD=changeme
    - POSTGRES_DB=demo
    
    ports:
    - '5432:5432'